# Training Configuration

# Model Configuration
model:
  name: "resnet"  # simple_cnn, resnet, mlp, transformer
  num_classes: 10
  pretrained: true

# Data Configuration
data:
  train_dir: "./data/raw/train"
  val_dir: "./data/raw/val"
  image_size: 224
  batch_size: 32
  num_workers: 4

# Training Configuration
training:
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"  # adam, sgd, adamw
  weight_decay: 0.0001
  
  # Scheduler
  scheduler:
    name: "reduce_on_plateau"  # reduce_on_plateau, cosine
    patience: 5
    factor: 0.5
  
  # Early Stopping
  early_stopping:
    enabled: true
    patience: 10
  
  # Device
  device: "cuda"  # cuda, cpu, mps

# Augmentation
augmentation:
  random_crop: true
  random_flip: true
  random_rotation: 15
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2

# Logging
logging:
  experiment_name: "my_experiment"
  save_dir: "./models/checkpoints"
  log_dir: "./logs"
  
  # Weights & Biases
  wandb:
    enabled: false
    project: "ai_ml_learning"
    entity: "your_username"
  
  # MLflow
  mlflow:
    enabled: false
    tracking_uri: "http://localhost:5000"
    experiment_name: "my_experiment"
